version: '2'

services:
    mongo:
        image: mongo
        ports:
            - 27017
    web:
        build: .
        command: npm start
        volumes:
            - .:/myapp
        ports:
            - 3000:3000
        links:
            - mongo
        environment:
            PORT: 3000